# Runs tests for all packages after pushes to main to check code coverage on a project level
name: Coverage

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpm test --all --coverage
