name: Unit tests

on: pull_request

permissions:
  contents: read

jobs:
  chrome:
    name: Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpm test
  firefox:
    name: Firefox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Install Playwright
        run: pnpx playwright install-deps firefox

      - name: Test
        run: pnpm run test:firefox
  webkit:
    name: WebKit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Install Playwright
        run: pnpx playwright install-deps webkit

      - name: Test
        run: pnpm run test:webkit
