name: Verify

on: pull_request

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint JavaScript
        run: pnpm run lint:js

      - name: Lint CSS
        run: pnpm run lint:css

      - name: Lint TypeScript
        run: pnpm run lint:types
  snapshots:
    name: Snapshot tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpm run test:snapshots
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpm run test:it
