name: Visual tests

on: pull_request

permissions:
  contents: read

jobs:
  lumo:
    name: Lumo
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vaadin'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Visual tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: pnpm run test:lumo

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: screenshots
          path: |
            packages/*/test/visual/lumo/screenshots/*/failed/*.png
            packages/vaadin-lumo-styles/test/visual/screenshots/failed/*.png
  material:
    name: Material
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vaadin'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Visual tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: pnpm run test:material

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: screenshots
          path: |
            packages/*/test/visual/material/screenshots/*/failed/*.png
            packages/vaadin-material-styles/test/visual/screenshots/failed/*.png
